Traceback (most recent call last):
  File "C:\Users\Lenovo\anaconda3\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\Lenovo\anaconda3\Lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\anaconda3\Lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\anaconda3\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\anaconda3\Lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "C:\Users\Lenovo\anaconda3\Lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\Lenovo\anaconda3\Lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import webbrowser
import time
import sys
stack = ListStack()
urls = [ "naver.com", "daum.net", "nate.com"]
# Browser history stacks up in the order in which you visit websites.
# push url of each visited websites to a stack
for url in urls:
  stack.push(url)
  # When you hit the back button, the previous URL is popped from the stack.
  stack.append(url)

while not len(stack)==0: # if stack is not empty
  url = stack.pop() # pop the previous URL and open the browser
  webbrowser.open('http://'+url)
------------------


[31m---------------------------------------------------------------------------[39m
[31mAttributeError[39m                            Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[10][39m[32m, line 11[39m
[32m      9[39m   stack.push(url)
[32m     10[39m   [38;5;66;03m# When you hit the back button, the previous URL is popped from the stack.[39;00m
[32m---> [39m[32m11[39m   [43mstack[49m[43m.[49m[43mappend[49m(url)
[32m     13[39m [38;5;28;01mwhile[39;00m [38;5;129;01mnot[39;00m [38;5;28mlen[39m(stack)==[32m0[39m: [38;5;66;03m# if stack is not empty[39;00m
[32m     14[39m   url = stack.pop() [38;5;66;03m# pop the previous URL and open the browser[39;00m

[31mAttributeError[39m: 'ListStack' object has no attribute 'append'

